# Generated by Django 4.2.3 on 2023-08-15 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_otpsecret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsecret',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_secret', to=settings.AUTH_USER_MODEL),
        ),
    ]
