# Generated by Django 4.2.3 on 2023-08-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_options_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyfacility',
            options={'verbose_name_plural': 'Property facilities'},
        ),
        migrations.AlterModelOptions(
            name='publicfacility',
            options={'verbose_name_plural': 'Public facilities'},
        ),
        migrations.AddField(
            model_name='property',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='home_facilities',
            field=models.ManyToManyField(blank=True, to='property.propertyfacility'),
        ),
        migrations.AlterField(
            model_name='property',
            name='public_facilities',
            field=models.ManyToManyField(blank=True, to='property.publicfacility'),
        ),
    ]
