# Generated by Django 4.2.3 on 2023-08-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tenantprofile_landlordprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
    ]
